apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-app-deployment
  labels:
    app: product-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: product-app
  template:
    metadata:
      labels:
        app: product-app
    spec:
      containers:
      - name: product-app
        image: web-api:latest
        ports:
        - containerPort: 80
